########## signup ##########

# POST http://localhost:4000/api/signup
# Content-Type: application/json

# {
#     "fullName": "admin admin",
#     "username": "admin",
#     "email": "admin@mail.com",
#     "password": "admin123"
# }



########## login ##########

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}